services:
  ocr:
    build: .
    ports:
      - "80"
    deploy:
      replicas: 1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ocr
    ports:
      - "80:80"
